artista/api/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls import url
from rest_framework import serializers,viewsets,routers

from .ViewSets.UserViewSet import UserViewSet,RoleViewSet
from .ViewSets.ArtistArtViewSet import ArtistArtViewSet,ArtCategoryViewSet


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'roles', RoleViewSet)
router.register(r'users', UserViewSet)
router.register(r'artist_art', ArtistArtViewSet)
router.register(r'art_category', ArtCategoryViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls'))
]

artista/app_artInfo/urls.py
from django.urls import path, include
from .views import AllArtView, AllArtSearchView, SingleArtView, SingleArtComment, ArtistArtReact, ArtistArtReactAllArt
from artist.views import SingleArtistView

app_name = "app_artInfo"
urlpatterns = [
    path('', AllArtView.as_view(), name='home'),  # landing page url
    path('single/<uuid>/', SingleArtView.as_view(),
         name='artist_single_art_page'),  # landing page url
    path('search/', AllArtSearchView.as_view(),
         name='all_art_searching_page'),  # Search Url
    path('comment/<image_uuid>/<type>', SingleArtComment.as_view(),
         name='artist_single_art_comment'),  # Search Url
    path('react/<uuid>/', ArtistArtReact.as_view(), name='artist_art_react'),
    path('my_loved_art/', ArtistArtReactAllArt.as_view(),
         name='artist_reacted_all_art'),
    path('artist/<uuid>', SingleArtistView.as_view(), name='single_artist_info'),
]

artista/artist/urls.py
from django.urls import path, include
from .views import DashboardArtistView, SingleArtistView, ArtistReviewView


app_name = "artist"
urlpatterns = [
    path('', DashboardArtistView.as_view(), name='home'),  # landing page url
    path('features/', include('artistArt.urls')),
    path('review/<uuid>', ArtistReviewView.as_view(), name='artist_review'),
]

artista/artistArt/urls.py
from django.urls import path ,include
from .views import ArtistArtUploadNew,ArtistArtPreview,ArtistArtUploadEdit,ArtistArtPreviewAll,ArtistArtUploadedDelete

urlpatterns = [
    path('upload/', ArtistArtUploadNew.as_view(), name='artist_art_upload'),
    path('upload/<uuid>/edit', ArtistArtUploadEdit.as_view(), name='artist_art_upload_edit'),
    path('upload/<uuid>/delete', ArtistArtUploadedDelete.as_view(), name='artist_art_uploaded_delete'),
    path('art_all/', ArtistArtPreviewAll.as_view(), name='artist_own_all_art'),
    path('art/<uuid>/', ArtistArtPreview.as_view(), name='artist_art_preview'),
]

artista/artista/urls.py
from django.contrib import admin
from django.urls import path, include

from getstart.views import home_view, HomePageView, blaBla, blaBlaadd
from register.views import register_client, register_artist, thank_you
from login.views import login_user, logout_user
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from forgotPass.views import ForgotPassword

admin.site.site_header = "ARTISTA Admin"
admin.site.site_title = "ARTISTA Admin Portal"
admin.site.index_title = "Welcome to ARTISTA Portal"

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),  # landing page url
    path('api/', include('api.urls')),  # api page url
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    # artist login page url app (login)
    path('login/', login_user, name='login_user'),
    # artist login page url app (login)
    path('logout/', logout_user, name='logout_user'),
    path('forgot_password/', include('forgotPass.urls')),

    # artist register page url  app (register)
    path('register/artist/', register_artist, name='register_artist'),
    # client register page url app (register)
    path('register/client/', register_client, name='register_client'),
    # artist register page url app (register)
    path('register/thankyou/', thank_you, name='register_thank_you'),


    path('dashboard/', include('dashboard.urls')),
    path('dashboard/artist/', include('artist.urls')),
    path('dashboard/client/', include('client.urls')),
    path('dashboard/art/', include('app_artInfo.urls')),
    #path('dashboard/art_artist/', include('artistArt.urls')),
    #path('dashboard/artist/api/art_artist/', include('artistArt.url_apis')),
     path('dashboard/profile', include('app_profileManagemant.urls')),

    path('category/', include('artistArtCategory.urls')),

    path('follow/', include('artistFollowing.urls')),

    path('chat/', include('chat.urls')),  # must need asynchronous server

    path('admin/', admin.site.urls),
    # path('bla-bla/', blaBla, name="bla-bla"),
    # path('add/', blaBlaadd, name="bla-bla-add"),

    # path('accounts/', include('allauth.urls')),
    path('dumy/', include('artistArt.url_apis')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

artista/artistArt/models.py
from django.db import models
import uuid
from datetime import datetime
from register.models import User
from artista.utils import get_current_user
import os
import uuid

# Create your models here.
class ArtCategory(models.Model):
   category_name=models.CharField(max_length=100,blank=False)

   def __str__(self):
        return self.category_name

def art_directory_stor_path(instance, filename):
    name, extension = os.path.splitext(filename)
    myDate = datetime.now()
    currentFilename = str(uuid.uuid4().hex)+ extension
    formatedDate = myDate.strftime("%Y-%m-%d")
    path = 'art_image/{0}/{1}'.format(formatedDate, currentFilename)
    return path

class ArtistArt(models.Model):
    STATUS = (
        ('public', 'Public'),
        ('draft', 'Draft'),
        ('private', 'Private')
    )
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    title=models.CharField(max_length=100,blank=False)
    short_description=models.CharField(max_length=300,blank=False)
    long_description=models.CharField(max_length=500,blank=False)
    tags=models.CharField(max_length=1000,blank=True)
    view_count=models.BigIntegerField(default=0)
    post_status = models.CharField(max_length=20,null=False,choices=STATUS,default='private')
    category = models.ForeignKey(ArtCategory, on_delete=models.CASCADE,null=False,blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=False,blank=False)
    image = models.ImageField(upload_to=art_directory_stor_path,default="art_image/default.jpg")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    __user_like_dislike = None

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.title

    @property
    def number_of_likes(self):
        find = ArtLikeDislike.objects.filter(artist_art=self,like_dislike=True)
        return find.count()

    @property
    def number_of_dislikes(self):
        find = ArtLikeDislike.objects.filter(artist_art=self,like_dislike=False)
        return find.count()
    
    def current_user_like_dislike(self,user_info):
        find = ArtLikeDislike.objects.filter(artist_art=self,user=user_info)
        if not find:
            find = None
            pass
        self.__user_like_dislike = find
        return find

    def current_art_comment(self):
        find = ArtComment.objects.filter(artist_art=self).order_by("-id")
        if not find:
            find = None
            pass
        return find


class ArtLikeDislike(models.Model):

    artist_art = models.ForeignKey(ArtistArt, on_delete=models.CASCADE,null=False,blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=False,blank=False)
    like_dislike = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.artist_art.title
    
    def save(self, *args, **kwargs):
        find = ArtLikeDislike.objects.filter(user=self.user , artist_art=self.artist_art)
        if find:
            get_data = find.get()
            if get_data.like_dislike == True :
                find.update(like_dislike = False)
            else:
                find.update(like_dislike = True)
                pass
        else:
            super().save(*args, **kwargs)
            
        
class ArtComment(models.Model):

    artist_art = models.ForeignKey(ArtistArt, on_delete=models.CASCADE,null=False,blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=False,blank=False)
    comment_message = models.CharField(max_length=255,blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment_message

artista/artistArt/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, Http404
from django.views import View
from artista.utils import get_current_user
from .forms import ArtistArtViewForm
from htmlmin.decorators import minified_response
from .models import ArtCategory, ArtistArt, ArtComment, ArtLikeDislike
from django.shortcuts import get_object_or_404


class ArtistArtUploadNew(View):
    """

    Atrist can upload a new art

    **Super Class**

        from django.views import View

    **Method User:**

       GET,POST

    **Context**

        user_info: register.User.\n
        form: artistArt.form.ArtistArtViewForm\n

    **Models that are used by this Class**

        The instance of model register.User.\n
        The instance of model artistArt.ArtistArt.\n

    **Template:**

        View Templates directory: artistArt/templates/artist_art_upload_form.html
    """

    USER_INFO = None

    def get(self, request, *args, **kwargs):
        self.USER_INFO = get_current_user(request)
        if self.USER_INFO == None:
            return redirect('/logout')
        form = ArtistArtViewForm(None)
        context = {
            'user_info': self.USER_INFO,
            'form': form
        }
        return render(request, 'artist_art_upload_form.html', context)

    def post(self, request, *args, **kwargs):
        self.USER_INFO = get_current_user(request)

        if self.USER_INFO == None:
            return redirect('/logout')

        form = ArtistArtViewForm(request.POST, request.FILES or None)
        form.setUser(current_user=self.USER_INFO)
        if form.is_valid():
            data = form.save()
            print(data)
            # return HttpResponse("Thank you to upload a new art code is = "+str(data.uuid))
            return redirect('artist:artist_own_all_art')

        context = {
            'user_info': self.USER_INFO,
            'form': form
        }
        return render(request, 'artist_art_upload_form.html', context)


class ArtistArtPreview(View):
    """
    Artist can see all his uploaded art and can select them for editing

    Atrist can upload a new art

    **Super Class**

        from django.views import View

    **Method User:**

        GET
    **Context**

        user_info: register.User.\n
        art_info: artistArt.ArtistArt.\n
        current_user_liked: artistArt.ArtLikeDislike\n

    **Models that are used by this Class**

        The instance of model register.User.\n
        The instance of model artistArt.ArtistArt.\n
        The instance of model artistArt.ArtLikeDislike.\n

    **Template:**

        View Templates directory: artistArt/templates/artist_art_preview.html
    """

    USER_INFO = None
    ART_INFO = None

    def get(self, request, *args, **kwargs):
        uid = kwargs.get('uuid')
        if not uid:
            raise Http404("Page not found")

        art = get_object_or_404(
            ArtistArt,  uuid=uid, post_status='public'
        )

        # ArtistArt.objects.get(
        #     uuid=uid,
        #     post_status='public'
        # )
        print("sadasdasdasd")

        if not art:
            raise Http404("Page not found")

        art.view_count = art.view_count + 1
        art.save()
        self.ART_INFO = art
        self.USER_INFO = get_current_user(request)

        if self.USER_INFO == None:
            return redirect('/logout')

        is_liked = None
        data = self.ART_INFO.current_user_like_dislike(self.USER_INFO)
        if data:
            is_liked = data.get().like_dislike

        context = {
            'user_info': self.USER_INFO,
            'art_info': self.ART_INFO,
            'current_user_liked': is_liked,
        }
        return render(request, 'artist_art_preview.html', context)


class ArtistArtUploadEdit(View):
    """
    Artist can Edit their uploaded art


    **Super Class**

        from django.views import View

    **Method User:**

        GET,POST
    **Context**

        user_info: register.User.\n
        form: artistart.form.ArtistArtViewForm\n

    **Models that are used by this Class**

        The instance of model register.User.\n
        The instance of model artistArt.ArtistArt.\n


    **Template:**

        View Templates directory: artistArt/templates/artist_art_upload_form.html
    """

    USER_INFO = None

    def get(self, request, *args, **kwargs):
        uid = kwargs.get('uuid')
        if not uid:
            raise Http404("Page not found")
        self.USER_INFO = get_current_user(request)
        if self.USER_INFO == None:
            return redirect('/logout')

        art = get_object_or_404(
            ArtistArt,  uuid=uid, user=self.USER_INFO
        )

        form = ArtistArtViewForm(instance=art)
        context = {
            'user_info': self.USER_INFO,
            'form': form
        }
        return render(request, 'artist_art_upload_form.html', context)

    def post(self, request, *args, **kwargs):
        uid = kwargs.get('uuid')
        if not uid:
            raise Http404("Page not found")
        self.USER_INFO = get_current_user(request)

        if self.USER_INFO == None:
            return redirect('/logout')
        art = get_object_or_404(
            ArtistArt,  uuid=uid, user=self.USER_INFO
        )

        form = ArtistArtViewForm(
            request.POST, request.FILES or None, instance=art)
        form.setUser(current_user=self.USER_INFO)
        if form.is_valid():
            data = form.save()
            return redirect('artist:artist_own_all_art')

        context = {
            'user_info': self.USER_INFO,
            'form': form
        }
        return render(request, 'artist_art_upload_form.html', context)


class ArtistArtUploadedDelete(View):
    """
    Artist can Delete their uploaded art

    **Super Class**

        from django.views import View

    **Method User:**

        GET

    **Models that are used by this Class**

        The instance of model register.User.\n
        The instance of model artistArt.ArtistArt.\n


    **Redirect:**

        View Redirect Url name: artistArt/templates/artist_art_upload_form.html
    """

    USER_INFO = None

    def get(self, request, *args, **kwargs):
        uid = kwargs.get('uuid')
        if not uid:
            raise Http404("Page not found")
        self.USER_INFO = get_current_user(request)

        if self.USER_INFO == None:
            return redirect('/logout')
        art = get_object_or_404(
            ArtistArt,  uuid=uid, user=self.USER_INFO
        )
        art.delete()
        return redirect('artist:artist_own_all_art')


class ArtistArtPreviewAll(View):
    """
    Artist can see  all art

    **Super Class**

        from django.views import View

    **Method User:**

        GET
    **Context**

        user_info: register.User.\n
        arts_info: artistArt.ArtistArt\n

    **Models that are used by this Class**

        The instance of model register.User.\n
        The instance of model artistArt.ArtistArt.\n


    **Template:**

        View Templates directory: artistArt/templates/artist_all_art_preview.html
    """

    USER_INFO = None
    ART_INFO = None

    def get(self, request, *args, **kwargs):

        self.USER_INFO = get_current_user(request)

        if self.USER_INFO == None:
            return redirect('/logout')

        art = ArtistArt.objects.filter(user=self.USER_INFO).order_by('-id')
        self.ART_INFO = art

        context = {
            'user_info': self.USER_INFO,
            'arts_info': self.ART_INFO,
        }
        return render(request, 'artist_all_art_preview.html', context)

artista/artistArt/templates/artist_all_art_preview.html
{% extends 'base_dashboard_header.html' %} {% load static %} 


{% block page_title %}
Artist All Arts
{% endblock %} 


{% block js_cdn %}

{% endblock %} 


{% block content %}
<div class="container my-5 text-center">
    <a href="{% url 'artist:artist_art_upload' %}" class="color1-btn">UPLOAD NEW ART</a>
</div>
<div class="container my-5">
    <div class="grid"> 
        {% if arts_info|length >= 1 %}
            {% for data in arts_info %}
            <div class="grid-item ">
                <!-- <div class="card mx-1" >
                            <img class="card-img-top" src="{{ data.image.url }}" alt="Card image cap">
                            <div class="card-body">
                            <h5 class="card-title">{{ data.title }}</h5>
                            <p class="card-text">{{ data.short_description }}</p>
                            <p class="card-text">view Count : {{ data.view_count }}</p>
                            <a href="{% url 'app_artInfo:artist_single_art_page'  data.uuid %}"  class="card-link" >View Art</a>
                            </div>
                        </div> -->
                      <div class="post-img">
          
                        <a href="{% url 'app_artInfo:artist_single_art_page'  data.uuid %}">
                            <img src="{{ data.image.url }}" alt="{{ data.title }}"/>
                            <div class="post-info">
                              <div class="user-profile">
                               
                                <div class="user-info">
                                  <h6>{{ data.title }}</h6>
                                  <p class="mb-0">{{ data.short_description }}</p>
                                </div>
                              </div>
                              <div>
                                <a href="{% url 'artist:artist_art_upload_edit'  data.uuid %}"  class="card-link" >Edit</a>
                                <a href="{% url 'artist:artist_art_uploaded_delete'  data.uuid %}" class="card-link">Delete</a>
                              </div>
                            </div>
                        </a>
          
                      </div>
              </div>
           
            {% endfor %}  
        {% else %}  
        <div class="container text-center">
            <h1 class="color1" >OOPS ! NO ART FOUND </h1>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}


{% block add_js %}
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script>
  
  // vanilla JS
// init with element
var grid = document.querySelector('.grid');
var msnry = new Masonry( grid, {
  // options...
  itemSelector: '.grid-item',
 
  itemSelector: '.grid-item',
  columnWidth: '.grid-sizer',
  percentPosition: true,
  gutter:15
});

// init with selector
var msnry = new Masonry( '.grid', {
  // options...
});
</script>
{% endblock %}

artista/artistArt/templates/artist_art_preview.html
{% extends 'base_dashboard_header.html' %} {% load static %} 

{% block meta %}
<!-- this file meta content -->
{% endblock %} 


{% block page_title %}
{{ art_info.title }}
{% endblock %} 


{% block js_cdn %}

{% endblock %} 


{% block content %}

<div class="container my-5">
  <div>
    title = {{ art_info.title }}
  </div>
  <div>
    short_description = {{ art_info.short_description }}
  </div>
  <div>
    view_count = {{ art_info.view_count }}
  </div>
  <div>
    long_description = {{ art_info.long_description }}
  </div>
  <div>
    category = {{ art_info.category | upper }}
  </div>
  <div>
   Tags = {{ art_info.tags | upper }}
  </div>
  <div>
    likes = {{ art_info.number_of_likes | upper }}
   </div>
   <div>
    dislikes = {{ art_info.number_of_dislikes | upper }}
   </div>
   <div>
    current_user_liked = {{ current_user_liked }}
   </div>
  <div>
     <img src="{{  art_info.image.url }}" class="rounded-circle" alt="Avatar" >
   </div>
</div>
{% endblock %}


{% block add_js %}
  <script>
  </script>
{% endblock %}

artista/artistArt/templates/artist_art_upload_form.html
{% extends 'base_dashboard_header.html' %} {% load static %} {% block page_title
%} Artist Upload Art {% block js_cdn %}
<script src="https://cdn.tiny.cloud/1/qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc/tinymce/5/tinymce.min.js"
  crossorigin="anonymous"></script>
{% endblock %} {% block content %}
<style>
  input#id_image {
    display: none;
  }

  label[for=id_image] {

    background: #5433FF;
    color: white;
    display: inline-block;
    padding: 0.75rem 3rem;
    border-radius: 3rem;
    border: 0.2rem solid #5433FF;
    -webkit-transition: background 200ms ease-out, color 200ms linear;
    transition: background 200ms ease-out, color 200ms linear;
  }

  label[for=id_image]:hover {
    cursor: pointer;
    background: transparent;
    color: #5433FF;
    
  }
  .cover{
    height: 250px;
    width: 170px;
    border: 1px solid #707070;
    border-radius: 3rem;
    overflow: hidden;
    display: flex;
    align-items: center;
    justify-content:center;
    margin-bottom: 2rem;
  }
  .cover img{
    height: 100%;
    width: 100%;
    object-fit: cover;
   
   
  }
  #camera-img{
    width: 40px;
    height: auto;
    object-fit: contain;
  }
  .form-control{
    border:0.1rem solid #707070;
    border-radius:0.75rem;
    font-size: 1.6rem; 
    
  }
  textarea {
      resize: none;
  }
  select {
  -webkit-appearance: none;
  -moz-appearance: none;
  background: transparent;
  background-image: url("data:image/svg+xml,<svg fill='rgb(84, 51, 255)' width='15' height='15' xmlns='http://www.w3.org/2000/svg'><path d='m0,6l7,7l7,-7l-15,0z'/><path fill='none' d='m0,0l15,0l0,15l-15,0l0,-15z'/></svg>");
  background-repeat: no-repeat;
  background-position-x: 90%;
  background-position-y: 1rem;
  border: 1px solid #707070;
  border-radius: 0.75rem;
  margin-right: 2rem;
  padding: 0.75rem ;
  padding-right: 4rem;
}
  @media(max-width: 767px){
    .form-group{
      text-align: center;
    }
    .cover {
      margin-left: auto;
      margin-right: auto;
    }
  }
</style>
<div class="container my-5">
  <div class="text-center mb-5">
    <h2>UPLOAD A NEW POST</h2>
  </div>
  <div class="cover">
      <img id="camera-img" src="{% static 'images/photography.png' %}"/>
  </div>

  <!-- add article form -->
  <div>
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {{error}}
    </div>
    {% endfor %}

    <form action="" method="POST" enctype="multipart/form-data">
      {% for field in form.visible_fields %}
      <div class="form-group">
        <label class="font-weight-bold" for="exampleInputEmail1">{{ field.label_tag }}</label>
        {{ field }} {% for error in field.errors %}
        <small id="emailHelp" class="form-text text-danger">{{ error }}</small>
        {% endfor %}
      </div>
      {% endfor %} {% csrf_token %} {% for hidden in form.hidden_fields %} {{
      hidden }} {% endfor %}
      <div class="text-center text-md-left">
        <button class="color1-btn " type="submit">
          Submit
        </button>
      </div>
    </form>
  </div>
  <!-- end add article form -->
</div>
{% endblock %} {% block add_js %}
<script>
  // tinymce.init({
  // selector: 'textarea#id_short_description',
  // });
  $(" label[for=id_image]").html("Select Image");
  $( "#id_title" ).removeClass( "form-control" )

  $(function () {
                // Multiple images preview in browser
                var imagesPreview = function (input, placeToInsertImagePreview) {

                    if (input.files) {
                        var filesAmount = input.files.length;

                        for (i = 0; i <1; i++) {
                            var reader = new FileReader();

                            reader.onload = function (event) {
                             
                              $(".cover > img").remove();
                                $($.parseHTML('<img id="cover-img">')).attr('src', event.target.result).appendTo(placeToInsertImagePreview);
                            }

                            reader.readAsDataURL(input.files[i]);
                        }
                    }

                };

               
                $('#id_image').on('change', function () {
                    imagesPreview(this, 'div.cover');
                });
            });
</script>

{% endblock %}