artista/api/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls import url
from rest_framework import serializers,viewsets,routers

from .ViewSets.UserViewSet import UserViewSet,RoleViewSet
from .ViewSets.ArtistArtViewSet import ArtistArtViewSet,ArtCategoryViewSet


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'roles', RoleViewSet)
router.register(r'users', UserViewSet)
router.register(r'artist_art', ArtistArtViewSet)
router.register(r'art_category', ArtCategoryViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls'))
]

artista/app_artInfo/urls.py
from django.urls import path, include
from .views import AllArtView, AllArtSearchView, SingleArtView, SingleArtComment, ArtistArtReact, ArtistArtReactAllArt
from artist.views import SingleArtistView

app_name = "app_artInfo"
urlpatterns = [
    path('', AllArtView.as_view(), name='home'),  # landing page url
    path('single/<uuid>/', SingleArtView.as_view(),
         name='artist_single_art_page'),  # landing page url
    path('search/', AllArtSearchView.as_view(),
         name='all_art_searching_page'),  # Search Url
    path('comment/<image_uuid>/<type>', SingleArtComment.as_view(),
         name='artist_single_art_comment'),  # Search Url
    path('react/<uuid>/', ArtistArtReact.as_view(), name='artist_art_react'),
    path('my_loved_art/', ArtistArtReactAllArt.as_view(),
         name='artist_reacted_all_art'),
    path('artist/<uuid>', SingleArtistView.as_view(), name='single_artist_info'),
]

artista/artista/urls.py
from django.contrib import admin
from django.urls import path, include

from getstart.views import home_view, HomePageView, blaBla, blaBlaadd
from register.views import register_client, register_artist, thank_you
from login.views import login_user, logout_user
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from forgotPass.views import ForgotPassword

admin.site.site_header = "ARTISTA Admin"
admin.site.site_title = "ARTISTA Admin Portal"
admin.site.index_title = "Welcome to ARTISTA Portal"

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),  # landing page url
    path('api/', include('api.urls')),  # api page url
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    # artist login page url app (login)
    path('login/', login_user, name='login_user'),
    # artist login page url app (login)
    path('logout/', logout_user, name='logout_user'),
    path('forgot_password/', include('forgotPass.urls')),

    # artist register page url  app (register)
    path('register/artist/', register_artist, name='register_artist'),
    # client register page url app (register)
    path('register/client/', register_client, name='register_client'),
    # artist register page url app (register)
    path('register/thankyou/', thank_you, name='register_thank_you'),


    path('dashboard/', include('dashboard.urls')),
    path('dashboard/artist/', include('artist.urls')),
    path('dashboard/client/', include('client.urls')),
    path('dashboard/art/', include('app_artInfo.urls')),
    #path('dashboard/art_artist/', include('artistArt.urls')),
    #path('dashboard/artist/api/art_artist/', include('artistArt.url_apis')),
     path('dashboard/profile', include('app_profileManagemant.urls')),

    path('category/', include('artistArtCategory.urls')),

    path('follow/', include('artistFollowing.urls')),

    path('chat/', include('chat.urls')),  # must need asynchronous server

    path('admin/', admin.site.urls),
    # path('bla-bla/', blaBla, name="bla-bla"),
    # path('add/', blaBlaadd, name="bla-bla-add"),

    # path('accounts/', include('allauth.urls')),
    path('dumy/', include('artistArt.url_apis')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

artista/app_artInfo/models.py
from django.db import models

# Create your models here.

artista/app_artInfo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views import View
from register.models import User
from artistArt.models import ArtistArt, ArtComment, ArtLikeDislike
from artista.utils import get_current_user
import django_filters
from django import forms
from django.db import models
from django.shortcuts import get_object_or_404
from artistArt.forms import ArtCommentForm
from django.contrib import messages
from django.db.models import Q
from artistFollowing.models import ArtistFollow


class ProductFilter(django_filters.FilterSet):
    """

    Custom made filtering class . Filter the arts and show then in the website  .

    **Super Class**
        from django_filters import FilterSet

    **Method User:**

        filter_by_order(self, queryset, value, name): return queryset\n
        search__in(self, queryset, value, name):return queryset\n

     **Models that are used by this Class**

        The instance of model artistArt.ArtistArt.\n


    """

    STATUS_CHOICES = (
        ("view_count", 'View Count ASC'),
        ("-view_count", 'View Count DESC'),
        ("-id", 'Recent Uploaded'),
    )

    search = django_filters.CharFilter(
        label="Search", max_length=255, method='search__in')
    ordering = django_filters.ChoiceFilter(
        label="Ordering", method='filter_by_order', choices=STATUS_CHOICES)

    class Meta:
        model = ArtistArt
        fields = ['category']

    def filter_by_order(self, queryset, value, name):
        if name:
            expression = name
            queryset = queryset.order_by(expression)
        return queryset

    def search__in(self, queryset, value, name):
        if name:
            expression = name
            queryset = queryset.filter(
                Q(title__icontains=expression) |
                Q(tags__icontains=expression) |
                Q(short_description__icontains=expression)|
                Q(category__category_name__icontains=expression)
            )
        return queryset


# Create your views here.
class AllArtSearchView(View):
    """

    Search all the arts by filtering them .the filters are bacically categorywise filter,choosing viewcount or latest uploded. Also can search by title or parial title.

    **Super Class**

        from django.views import View

    **Method User:**

       GET

    **Context**

        user_info: register.User.\n
        filter: app_artinfo.View.ProductFilter.\n

    **Models that are used by this Class**

        The instance of model register.User.\n
        The instance of model artistArt.ArtistArt.\n

    **Template:**

        View Templates directory: artistArt/templates/all_art_preview_search.html
    """

    def get(self, request, *args, **kwargs):
        user = get_current_user(request)
        if not user:
            return redirect('/')

        user = get_current_user(request)
        f = ProductFilter(
            request.GET,
            queryset=ArtistArt.objects.filter(post_status="public")
        )
        context = {
            'user_info': user,
            'filter': f
        }
        return render(request, "all_art_preview_search.html", context)

    def post(self, request, *args, **kwargs):
        pass


# Create your views here.
class AllArtView(View):
    """

    Display all the artist's public arts

    **Super Class**

        from django.views import View

    **Method User:**

       GET

    **Context**

        user_info: register.User.\n
        "allArts": artistArt.ArtistArt.\n

    **Models that are used by this Class**

        The instance of model register.User.\n
        The instance of model artistArt.ArtistArt.\n

    **Template:**

        View Templates directory: artistArt/templates/all_art_preview.html
    """

    def get(self, request, *args, **kwargs):
        user = get_current_user(request)
        if not user:
            return redirect('/')

        art = ArtistArt.objects.filter(post_status="public")

        context = {
            'user_info': user,
            "allArts": art,
        }
        return render(request, "all_art_preview.html", context)


# Create your views here.
class SingleArtView(View):
    """
    Displaing a specific art with comment, react, artist info etc

    **Super Class**

        from django.views import View

    **Method User:**

       GET

    **Context**

        'user_info': registe.User,\n
        'art_info': artistArt.ArtistArt,\n
        'current_user_liked': artistArt.ArtLikeDislike,\n
        'art_comments': artistArt.ArtComment,\n
        'art_comments_form': ArtCommentForm.form,\n
        'is_current_user_following': artistFollowing.ArtistFollow\n

    **Models that are used by this Class**

        The instance of model register.User.\n
        The instance of model artistArt.ArtistArt.\n
        The instance of model artistArt.ArtLikeDislike.\n
        The instance of model artistArt.ArtComment.\n
        The instance of model artistFollowing.ArtistFollow.\n

    **Template:**

        View Templates directory: app_artInfo\\templates\single_art_preview.html
    """

    def get(self, request, *args, **kwargs):
        uid = kwargs.get('uuid')
        if not uid:
            raise Http404("Page not found")

        art = get_object_or_404(
            ArtistArt,  uuid=uid, post_status='public'
        )
        user = get_current_user(request)
        if not user:
            return redirect('/')

        art.view_count = art.view_count + 1
        art.save()
        ART_INFO = art

        is_liked = False
        data = ART_INFO.current_user_like_dislike(user)
        if data:
            is_liked = data.get().like_dislike

        is_current_user_following = False
        data = ArtistFollow.objects.filter(
            user_following=ART_INFO.user)
        if data:
            is_current_user_following = True

        comment = ART_INFO.current_art_comment()
        form = ArtCommentForm(None)

        context = {
            'user_info': user,
            'art_info': ART_INFO,
            'current_user_liked': is_liked,
            'art_comments': comment,
            'art_comments_form': form,
            'is_current_user_following': is_current_user_following,
        }
        return render(request, "single_art_preview.html", context)

    def post(self, request, *args, **kwargs):
        pass


# Create your views here.
class SingleArtComment(View):
    """
    Comment submission using a form

    **Super Class**

        from django.views import View

    **Method User:**

        POST


    **Models that are used by this Class**

        The instance of model register.User.\n
        The instance of model artistArt.ArtComment.\n

    **Redirect to:**
        artist_single_art_page
    """

    def post(self, request, *args, **kwargs):
        uid = kwargs.get('image_uuid')
        typ = kwargs.get('type')
        if not uid:
            raise Http404("Page not found")
        if not typ:
            raise Http404("Page not found")
        user = get_current_user(request)
        if not user:
            return redirect('/')
        if typ == "delete":
            comment_id = request.POST.get("comment_id")
            comment = get_object_or_404(
                ArtComment,  id=comment_id
            )
            comment.delete()
            messages.error(request, " Comment is deleted")

        elif typ == "add":
            art = get_object_or_404(
                ArtistArt,  uuid=uid, post_status='public'
            )
            form = ArtCommentForm(request.POST)
            form.setUser(user)
            form.setArt(art)

            if form.is_valid():
                form.save(commit=True)

            else:
                messages.error(request, " Please give correct comment ")

        return redirect("app_artInfo:artist_single_art_page", uid)


class ArtistArtReact(View):
    """
    React on a existing public art.Record the react 

    **Super Class**

        from django.views import View

    **Method User:**

        POST


    **Models that are used by this Class**

        The instance of model register.User.\n
        The instance of model artistArt.ArtLikeDislike.\n

    **Redirect to:**
        artist_single_art_page
    """

    USER_INFO = None
    ART_INFO = None

    def post(self, request, *args, **kwargs):
        uid = kwargs.get('uuid')
        if not uid:
            raise Http404("Page not found")

        self.USER_INFO = get_current_user(request)

        if self.USER_INFO == None:
            return redirect('/logout')

        art = ArtistArt.objects.get(uuid=uid)
        saveData = ArtLikeDislike()
        saveData.artist_art = art
        saveData.user = self.USER_INFO
        saveData.save()

        return redirect("app_artInfo:artist_single_art_page", uid)


class ArtistArtReactAllArt(View):
    """
    Show all the reacted art of currently logged-in user

    **Super Class**

        from django.views import View

    **Method User:**

        GET

    **Context**

        user_info: register.user,\n
        allLovedArts: artistArt.ArtLikeDislike,\n

    **Models that are used by this Class**

        The instance of model register.User.\n
        The instance of model artistArt.ArtistArt.\n

    **Template:**

        View Templates directory: artistArt/templates/all_reacted_art.html
    """

    def get(self, request, *args, **kwargs):

        user = get_current_user(request)

        all_Loved_Arts = ArtLikeDislike.objects.filter(
            Q(user=user), Q(like_dislike=True))

        context = {
            'user_info': user,
            "allLovedArts": all_Loved_Arts,
        }

        return render(request, "all_reacted_art.html", context)

artista/app_artInfo/templates/all_art_preview.html
{% extends 'base_dashboard_header.html' %} {% load static %}


{% block page_title %}
Artist All Arts
{% endblock %}


{% block js_cdn %}

{% endblock %}


{% block content %}

<style>
  #id_title{
    width:100%;
  }
  .input-group input{
  border-radius: 3rem;
    width: 100%;
    padding: 0.75rem 3rem;
    border: 1px solid #707070;   
  }
  
</style>
<div class="container text-center">
<form class="form-inline" action="{% url 'app_artInfo:all_art_searching_page' %}">
  
  <div class="input-group col">
    <input type="text" name="search" class="" maxlength="100" required id="id_title"> 
   
  </div>

  <div class="text-center text-md-left">
    <button class="color1-btn " type="submit">
      Search
    </button>
  </div>
</form>

</div>


<div class="container my-5">
  <div class="grid">

    {% for data in allArts %}
    <div class="grid-item ">
      <!-- <div class="card mx-1" >
                  <img class="card-img-top" src="{{ data.image.url }}" alt="Card image cap">
                  <div class="card-body">
                  <h5 class="card-title">{{ data.title }}</h5>
                  <p class="card-text">{{ data.short_description }}</p>
                  <p class="card-text">view Count : {{ data.view_count }}</p>
                  <a href="{% url 'app_artInfo:artist_single_art_page'  data.uuid %}"  class="card-link" >View Art</a>
                  </div>
              </div> -->
            <div class="post-img">

              <a href="{% url 'app_artInfo:artist_single_art_page'  data.uuid %}">
                  <img src="{{ data.image.url }}" alt="{{ data.title }}"/>
                  <div class="post-info">
                    <div class="user-profile">
                      <img src="{{ data.user.avatar.url }}"/>
                      <div class="user-info">
                        <h6>{{ data.user.display_name }}</h6>
                        
                      </div>
                    </div>
                    <h4 class="px-2 text-center">Category: {{ data.category }}</h4>
                    <p class="fas fa-eye color1 mb-0">{{ data.view_count }}</p>
                  </div>
              </a>

            </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}


{% block add_js %}
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script>
  
  // vanilla JS
// init with element
var grid = document.querySelector('.grid');
var msnry = new Masonry( grid, {
  // options...
  itemSelector: '.grid-item',
 
  itemSelector: '.grid-item',
  columnWidth: '.grid-sizer',
  percentPosition: true,
  gutter:15
});

// init with selector
var msnry = new Masonry( '.grid', {
  // options...
});
</script>
{% endblock %}

artista/app_artInfo/templates/all_art_preview_search.html
{% extends 'base_dashboard_header.html' %} {% load static %}


{% block page_title %}
Artist All Arts
{% endblock %}


{% block js_cdn %}

{% endblock %}


{% block content %}
<style>
  .form-inline p {
  
  }

  #id_search {
    border: 1px solid #707070;
    border-radius: 0.75rem;

    padding: 0.75rem;
  }
  select{
    margin-right: 0px;
  }
  .form-inline label{
    font-size: 2rem;
    padding-bottom: 1rem;
    font-weight: 600;
  }
  @media(min-width: 768px) {
    .form-inline {
      justify-content: space-evenly;
    }
  }

  @media(max-width:767px) {
    .form-inline .color1-btn {
      width: 100%;
    }

    .form-inline p {
      display: flex;
      align-items: center;
      width: 100%;
    }

    .form-inline input,
    .form-inline select {
      flex-grow: 1;
      margin-left: 1rem;
      margin-right: 0;
    }

    .form-inline label {
      width: 30%;
    }
   
  }
</style>
<div class="container">
  <form class="form-inline" method="get">
    {{ filter.form.as_p }}
    <input class="color1-btn" type="submit" />
  </form>
</div>



<div class="container my-5">
  <div class="grid">

    {% for data in filter.qs %}
    <div class="grid-item ">
      <!-- <div class="card mx-1" >
                    <img class="card-img-top" src="{{ data.image.url }}" alt="Card image cap">
                    <div class="card-body">
                    <h5 class="card-title">{{ data.title }}</h5>
                    <p class="card-text">{{ data.short_description }}</p>
                    <p class="card-text">view Count : {{ data.view_count }}</p>
                    <a href="{% url 'app_artInfo:artist_single_art_page'  data.uuid %}"  class="card-link" >View Art</a>
                    </div>
                </div> -->
      <a href="{% url 'app_artInfo:artist_single_art_page'  data.uuid %}">
        <div class="post-img">

          <a href="{% url 'app_artInfo:artist_single_art_page'  data.uuid %}">
            <img src="{{ data.image.url }}" alt="{{ data.title }}" />
            <div class="post-info">
              <div class="user-profile">
               
                <div class="user-info">
                  <h6>{{ data.title }}</h6>
                  <p class="mb-0">{{ data.short_description }}</p>
                </div>
              </div>

              <p class="fas fa-eye color1 mb-0">{{ data.view_count }}</p>
            </div>
          </a>

        </div>
      </a>
    </div>
    {% endfor %}
  </div>

</div>
{% endblock %}


{% block add_js %}
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script>
  
  // vanilla JS
// init with element
var grid = document.querySelector('.grid');
var msnry = new Masonry( grid, {
  // options...
  itemSelector: '.grid-item',
 
  itemSelector: '.grid-item',
  columnWidth: '.grid-sizer',
  percentPosition: true,
  gutter:15
});

// init with selector
var msnry = new Masonry( '.grid', {
  // options...
});
</script>
{% endblock %}

artista/app_artInfo/templates/all_reacted_art.html
{% extends 'base_dashboard_header.html' %} {% load static %} 


{% block page_title %}
All Reacted Art
{% endblock %} 


{% block js_cdn %}

{% endblock %} 


{% block content %}


  <div class="container my-5">
      <div class="grid">
            {% for data in allLovedArts %}
              <div class="grid-item ">
                <a href="{% url 'app_artInfo:artist_single_art_page'  data.artist_art.uuid %}">
                  <div class="post-img">
          
                   
                      <img src="{{ data.artist_art.image.url }}" alt="{{ data.title }}" />
                      <div class="post-info">
                        <div class="user-profile">
                         
                          <div class="user-info">
                            <h6>{{ data.artist_art.title }}</h6>
                            <p class="mb-0">{{ data.artist_art.short_description }}</p>
                          </div>
                        </div>
          
                       
                      </div>

          
                  </div>
                </a>
              </div>
              {% endfor %}  
      </div>
  </div>
{% endblock %}


{% block add_js %}
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script>
  
  // vanilla JS
// init with element
var grid = document.querySelector('.grid');
var msnry = new Masonry( grid, {
  // options...
  itemSelector: '.grid-item',
 
  itemSelector: '.grid-item',
  columnWidth: '.grid-sizer',
  percentPosition: true,
  gutter:15
});

// init with selector
var msnry = new Masonry( '.grid', {
  // options...
});
</script>
{% endblock %}

artista/app_artInfo/templates/single_art_preview.html
{% extends 'base_dashboard_header.html' %} {% load static %}


{% block page_title %}
Artist All Arts
{% endblock %}


{% block js_cdn %}

{% endblock %}

{% block content %}


<style>
  .profile-block img {
    width: 125px;
    height: calc(125px + 1rem);

  }

  .font-700 {
    font-weight: 700;
  }

  .img-small {
    height: 80px;
    width: 80px;
  }
  .btn.color2:hover{
    color:#20BDFF;
    filter: brightness(120%);
  }
</style>
<div class="container pt-5 ">


  <div class="row">
    <div class="col-md-6 ">
      <img class="img-fluid" src="{{  art_info.image.url }}" class="" alt="Avatar">
    </div>
    <div class="col-md-6 ">


      <div class="profile-block d-flex align-items-center align-items-xl-start">

        <a class="text-dark" href="{% url 'app_artInfo:single_artist_info'  art_info.user.uuid %}">
          <img class="profile-img py-3" src="{{ art_info.user.avatar.url }}" alt="avatar" />
          <div class="profile-info d-flex flex-wrap flex-grow-1">

            <div class="py-3 pr-5 pl-4">
              <h5 class="text-black mb-0">{{ art_info.user.display_name }}</h5>


            </div>
            <div class="flex-grow-1 p-3">

              {% if user_info != art_info.user %}
              <form action="{% url 'artist_follow_form_submit'  art_info.user.uuid %}" method="POST">
                {% csrf_token %}

                <input type="hidden" name="art" value='{{art_info.uuid}}'>

                {% if is_current_user_following %}
                <button type="submit" class="color1-btn ">Unfollow</button>
                {% else %}
                <button type="submit" class="color1-btn ">Follow</button>

                {% endif %}
              </form>
              {% endif %}
            </div>

        </a>
      </div>

    </div>

    <h3>
      {{ art_info.title }}
    </h3>
    <p>
      short_description = {{ art_info.short_description }}
    </p>
    <h5 class="font-700">Category:</h5>
    <p> {{ art_info.category | upper }}</p>
    {% if current_user_liked %}
    <form action="{%  url 'app_artInfo:artist_art_react' art_info.uuid %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-default color-2 ">
        <h3>
          <i class="fas fa-heart color1"></i>
        </h3>
      </button>
    </form>
    {% else %}
    <form action="{%  url 'app_artInfo:artist_art_react' art_info.uuid %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-default color2">
        <h3>
          <i class="fas fa-heart"></i>
        </h3>
      </button>
    </form>
    {% endif %}
  </div>

</div>
<!-- <h4 class="mt-4 font-700">Tags</h4>
<h6> Tags = {{ art_info.tags | upper }}</h6> -->
<h4 class="mt-5 font-700">Description</h4>
<p>  {{ art_info.long_description }}</p>
<h4 class="my-5 font-700">Comment</h4>
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger" role="alert">
  {{message}}
</div>
{% endfor %}
{% endif %}
{% for error in art_comments_form.non_field_errors %}
<div class="alert alert-danger" role="alert">
  {{error}}
</div>
{% endfor %}
<form class="form-inline align-items-start mb-5"
  action="{%  url 'app_artInfo:artist_single_art_comment' art_info.uuid 'add'%}" method="POST">
  {% for field in art_comments_form.visible_fields %}
  <div class="form-group col-md-6 col-lg-6">
    <!-- <label class="font-weight-bold" for="exampleInputEmail1">{{ field.label_tag }}</label> -->
    {{ field }}
    {% for error in field.errors %}
    <small id="emailHelp" class="form-text text-danger">{{ error }}</small>
    {% endfor %}
  </div>
  {% endfor %}

  {% csrf_token %}

  {% for hidden in form.hidden_fields %}
  {{ hidden }}
  {% endfor %}
  <div class="px-md-4">
    <button class="color1-btn " style="width: 150px;" type="submit">Submit</button>
  </div>

</form>


{% for data in art_comments %}
<div class="row m-0 mb-5">
  <div class="col flex-grow-0">
    <a href="{% url 'app_artInfo:single_artist_info'  data.user.uuid %}">
      <img class="profile-img img-small" src="{{ data.user.avatar.url }}" alt="{{ data.user.display_name }}">
    </a>  
  </div>
  <div class="col">
    <h5 class="mb-3">{{ data.user.display_name }}</h5>
    <p class="mb-3">{{ data.comment_message }}</p>
    {% if user_info == data.user %}
    <form action="{%  url 'app_artInfo:artist_single_art_comment' art_info.uuid 'delete'%}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="comment_id" value="{{ data.id }}">
      <button type="submit" class=" btn btn-link color1 color1-hover">Delete</button>
    </form>
    {% endif %}
  </div>
</div>
{% endfor %}



<!-- <div>
     
        <img src="{{  art_info.image.url }}" class="" alt="Avatar" >
      </div>
    <div>
      title = {{ art_info.title }}
    </div>
    <div>
      short_description = {{ art_info.short_description }}
    </div>
    <div>
      view_count = {{ art_info.view_count }}
    </div>
    <div>
      long_description = {{ art_info.long_description }}
    </div>
    <div>
      category = {{ art_info.category | upper }}
    </div>
    <div>
     Tags = {{ art_info.tags | upper }}
    </div>
    <div>
      likes = {{ art_info.number_of_likes | upper }}
     </div>
     <div>
      dislikes = {{ art_info.number_of_dislikes | upper }}
     </div>
     <div>
      current_user_liked = {{ current_user_liked }}
     </div> -->

</div>





{% endblock %}


{% block add_js %}
<script>
</script>
{% endblock %}