artista/api/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls import url
from rest_framework import serializers,viewsets,routers

from .ViewSets.UserViewSet import UserViewSet,RoleViewSet
from .ViewSets.ArtistArtViewSet import ArtistArtViewSet,ArtCategoryViewSet


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'roles', RoleViewSet)
router.register(r'users', UserViewSet)
router.register(r'artist_art', ArtistArtViewSet)
router.register(r'art_category', ArtCategoryViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls'))
]

artista/app_profileManagemant/urls.py
from django.urls import path ,include
from .views import UsersProfileEdit

app_name="app_profileManagemant"
urlpatterns = [
    path('', UsersProfileEdit.as_view(), name='home'), #landing page url
]

artista/artista/urls.py
from django.contrib import admin
from django.urls import path, include

from getstart.views import home_view, HomePageView, blaBla, blaBlaadd
from register.views import register_client, register_artist, thank_you
from login.views import login_user, logout_user
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from forgotPass.views import ForgotPassword

admin.site.site_header = "ARTISTA Admin"
admin.site.site_title = "ARTISTA Admin Portal"
admin.site.index_title = "Welcome to ARTISTA Portal"

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),  # landing page url
    path('api/', include('api.urls')),  # api page url
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    # artist login page url app (login)
    path('login/', login_user, name='login_user'),
    # artist login page url app (login)
    path('logout/', logout_user, name='logout_user'),
    path('forgot_password/', include('forgotPass.urls')),

    # artist register page url  app (register)
    path('register/artist/', register_artist, name='register_artist'),
    # client register page url app (register)
    path('register/client/', register_client, name='register_client'),
    # artist register page url app (register)
    path('register/thankyou/', thank_you, name='register_thank_you'),


    path('dashboard/', include('dashboard.urls')),
    path('dashboard/artist/', include('artist.urls')),
    path('dashboard/client/', include('client.urls')),
    path('dashboard/art/', include('app_artInfo.urls')),
    #path('dashboard/art_artist/', include('artistArt.urls')),
    #path('dashboard/artist/api/art_artist/', include('artistArt.url_apis')),
     path('dashboard/profile', include('app_profileManagemant.urls')),

    path('category/', include('artistArtCategory.urls')),

    path('follow/', include('artistFollowing.urls')),

    path('chat/', include('chat.urls')),  # must need asynchronous server

    path('admin/', admin.site.urls),
    # path('bla-bla/', blaBla, name="bla-bla"),
    # path('add/', blaBlaadd, name="bla-bla-add"),

    # path('accounts/', include('allauth.urls')),
    path('dumy/', include('artistArt.url_apis')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

artista/app_profileManagemant/models.py
from django.db import models

# Create your models here.

artista/app_profileManagemant/forms.py
from django import forms
from register.models import User
from django.contrib.auth.hashers import make_password, check_password
from django.utils.translation import gettext, gettext_lazy as _
import uuid
from django.db.models import Q


class UserEditProfile(forms.ModelForm):

    """
    A form that generates Custom UserEdit form

    **Super Class**

        from django import forms

    **Method User:**

        clean_image(self): raise forms.ValidationError\n
        def clean_email(self): return email.lower()\n
        save(self, commit=True): return usr\n


    **Models that are used by this Class**

        The instance of model register.User.\n

    ** Generated Form Field **

        'display_name',\n
        'email',\n
        'phoneNumber',\n
        'address',\n
        'avatar',\n
        'short_bio',\n

    """

    email = forms.CharField(label="Email",
                            widget=forms.EmailInput(
                                attrs={'class': '', }
                            ),
                            max_length=100, required=True)

    display_name = forms.CharField(label="Display name",
                                   widget=forms.TextInput(
                                       attrs={
                                           'class': '', }
                                   ),
                                   max_length=30, required=True)

    address = forms.CharField(label="Address",
                              widget=forms.TextInput(
                                  attrs={
                                      'class': '', }
                              ),
                              max_length=255, required=True)

    phoneNumber = forms.CharField(label="Phone Number",
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': '', }
                                  ),
                                  max_length=20, required=True)

    avatar = forms.ImageField(label="Profile Picture", required=True)

    def clean_image(self):
        image = self.cleaned_data.get('avatar')
        if image:
            if image.size > 1*1024*1024:
                raise forms.ValidationError("Image file too large ( > 1mb )")
            return image
        else:
            raise forms.ValidationError("Couldn't read uploaded image")

    def clean_email(self):
        email = self.cleaned_data['email']
        return email.lower()

    def save(self, commit=True):
        usr = super(UserEditProfile, self).save(commit=False)
        if commit:
            usr.save()
        return usr

    class Meta:
        model = User
        fields = [
            'display_name',
            'email',
            'phoneNumber',
            'address',
            'avatar',
            'short_bio',
        ]

artista/app_profileManagemant/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views import View
from register.models import User
from artistArt.models import ArtistArt, ArtComment, ArtLikeDislike
from artista.utils import get_current_user
import django_filters
from django import forms
from django.db import models
from django.shortcuts import get_object_or_404
from artistArt.forms import ArtCommentForm
from django.contrib import messages
from .forms import UserEditProfile

# Create your views here.


# Create your views here.
class UsersProfileEdit(View):
    """
    Edit the profile of currently logged-in user

    **Super Class**

        from django.views import View

    **Method User:**

        GET,POST

    **Context**

        user_info: register.user,\n
        form: app_profileManagement.form.UserEditProfile\n    

    **Models that are used by this Class**

        The instance of model register.User.\n


    **Template:**

        View Templates directory: app_profileManagement/templates/user_profile_edit.html
    """

    def get(self, request, *args, **kwargs):
        user = get_current_user(request)
        if not user:
            return redirect('/logout')
        form = UserEditProfile(instance=user)
        context = {
            'user_info': user,
            'form': form
        }
        return render(request, "user_profile_edit.html", context)

    def post(self, request, *args, **kwargs):
        user = get_current_user(request)
        if not user:
            return redirect('/logout')

        form = UserEditProfile(
            request.POST, request.FILES or None, instance=user)

        if form.is_valid():
            data = form.save()
            return redirect('app_profileManagemant:home')

        context = {
            'user_info': user,
            'form': form
        }
        return render(request, 'user_profile_edit.html', context)

artista/app_profileManagemant/templates/user_profile_edit.html
{% extends 'base_dashboard_header.html' %} {% load static %}


{% block page_title %}
Artist All Arts
{% endblock %}


{% block js_cdn %}

{% endblock %}


{% block content %}
<style>
  input#id_avatar {
    display: none;
  }

  label[for=id_avatar] {

    color: #5433FF;
    background: transparent;
    display: inline-block;
    padding: 0.75rem 3rem;
    border-radius: 3rem;
    border: 0.2rem solid #5433FF;
    -webkit-transition: background 200ms ease-out, color 200ms linear;
    transition: background 200ms ease-out, color 200ms linear;
  }

  label[for=id_avatar]:hover {
    cursor: pointer;
    color: white;
    background: #5433FF;
    
  }
  .cover{
    height: 250px;
    width: 170px;
    border: 1px solid #707070;
    border-radius: 3rem;
    overflow: hidden;
    display: flex;
    align-items: center;
    justify-content:center;
    margin-bottom: 2rem;
  }
  .cover img{
    height: 100%;
    width: 100%;
    object-fit: cover;
   
   
  }
  #camera-img{
    width: 40px;
    height: auto;
    object-fit: contain;
  }
  .form-control{
    border:0.1rem solid #707070;
    border-radius:0.75rem;
    font-size: 1.6rem; 
    
  }
  textarea {
      resize: none;
  }
</style>
  
  <!-- User Profile  edit -->
  <div class="container my-5">
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {{error}}
    </div>
    {% endfor %}

    <form action="" method="POST" enctype="multipart/form-data">
      {% for field in form.visible_fields %}
      <div class="form-group">
        <label class="font-weight-bold" for="exampleInputEmail1">{{ field.label_tag }}</label>
        {{ field }} {% for error in field.errors %}
        <small id="emailHelp" class="form-text text-danger">{{ error }}</small>
        {% endfor %}
      </div>
      {% endfor %} {% csrf_token %} {% for hidden in form.hidden_fields %} {{
      hidden }} {% endfor %}
      <div class="text-center text-md-left">
        <button class="color1-btn " type="submit">
          Submit
        </button>
      </div>
    </form>
  </div>
  <!-- User Profile  edit  -->

{% endblock %}


{% block add_js %}
<script>
  $("label[for=id_avatar").prepend('<div class="dp "></div>'); 
   $(" label[for=id_avatar]").html("Upload Photo");
  $( ".form-control input" ).removeClass( "form-control" )

  $(function () {
                // Multiple images preview in browser
                var imagesPreview = function (input, placeToInsertImagePreview) {

                    if (input.files) {
                        var filesAmount = input.files.length;

                        for (i = 0; i <1; i++) {
                            var reader = new FileReader();

                            reader.onload = function (event) {
                             
                             // $(".cover > img").remove();
                                $($.parseHTML('<img id="cover-img">')).attr('src', event.target.result).appendTo(placeToInsertImagePreview);
                            }

                            reader.readAsDataURL(input.files[i]);
                        }
                    }

                };

               
                $('#id_avatar').on('change', function () {
                    imagesPreview(this, 'div.dp');
                });
            });
</script>
{% endblock %}